Low hanging fruit
artizen-fund/artizen-frontend pull request #316
Opened 2022-12-21 01:37 UTC by EricWVGG

- removed unused Perks component
- FeaturedArtPanel correctly formats starting/ending grant dates
- AccountButton is no longer clickable before JWT is read, and presents a spinner
- UploadFileControl improvements…
  - uses InviseFileInput from AvatarUpload to for drag-and-drop images and DRY
  - uses existing text inputs to show cloudinary url
  - shows image and video previews on right

old UploadFileControl had some notes about memory leaks, but didn't actually do anything about them. Let me know if I should deeper investigate.

2022-12-21 10:30 UTC, rubelux requested changes
In `page/admin/grants` line 50, it gets stuck on the spinning component, it should only display the spinner if there is  user session being loaded otherwise it needs to display a message inviting user to login "with a curator account"

2022-12-21 10:36 UTC, rubelux requested changes
in `pages/admin/grants/` fix the rollover call on dark theme

<img width="991" alt="Screenshot 2022-12-21 at 11 31 16" src="https://user-images.githubusercontent.com/1488156/208885160-73c1cc3d-f3a6-4182-86fd-f44f84501311.png">

2022-12-21 10:38 UTC, rubelux requested changes
in `pages/admin/grants/` Set a maximum height to the list container and make the item scroll vertically within

2022-12-21 11:41 UTC, rubelux requested changes

2022-12-21 11:41 UTC, rubelux commented on src/components/Form/Controls/UploadFileControl/index.tsx
> -        <ImageWrapper>
* The image wrapper is not expanding to 300px 
* Make the component height to 300px 
* hide the image link 
* Hide the component label
* Center the uploaded image in the centre of the box



<img width="467" alt="Screenshot 2022-12-21 at 11 58 41" src="https://user-images.githubusercontent.com/1488156/208890240-52f1c32a-9417-4743-9c49-9014e6559c46.png">

2022-12-21 15:51 UTC, EricWVGG commented on src/components/Form/Controls/UploadFileControl/index.tsx
> -        <ImageWrapper>
The design of this was deliberate, I wanted to keep it consistent with our existing forms and have the input accurately reflect what was being recorded. Also if we want a proper design, I think that would be a task for Simon or Juju, and I don't want to put anything on their plate right now.

Would you mind if I instead made the image preview clickable, and it launches a popup where the asset is full-sized? We already have the component for that, it should be an easy drop-in.

2022-12-22 02:17 UTC, EricWVGG commented on src/components/Form/Controls/UploadFileControl/index.tsx
> -        <ImageWrapper>
I've added a preview modal for media. I think you'll like it!

2022-12-22 10:30 UTC, rubelux commented on src/components/Form/Controls/UploadFileControl/index.tsx
> +            <source src={data} type="video/mp4" />
@EricWVGG I do not see WebM in the Video type list

2022-12-22 10:30 UTC, rubelux commented on src/components/Form/Controls/UploadFileControl/index.tsx
> +    uploadFile(selectedFile)
@EricWVGG this is still happening

2022-12-22 10:32 UTC, rubelux commented on src/components/Form/Controls/UploadFileControl/index.tsx
> -        <ImageWrapper>
All the NFTs assets are all square, so we need these boxes to be square now. Can you make them square? 
Also, they label and the text is still shows up,

2022-12-22 10:42 UTC, rubelux requested changes
@EricWVGG VIdeos are to uploaded to Cloudinary, Component shows an error

2022-12-22 11:05 UTC, rubelux commented on src/components/Form/Controls/UploadFileControl/index.tsx
> +            <source src={data} type="video/mp4" />
Cloudinary will deliver WebM to Chrome browsers

2022-12-22 14:12 UTC, EricWVGG commented on src/components/Form/Controls/UploadFileControl/index.tsx
> -        <ImageWrapper>
^ try clicking the image for a preview popup. Much better than 300px wrapper.

The preview boxes in the corner do not force square images.

The URL is there in the value for a reason — it's what we're actually storing.

2022-12-22 14:12 UTC, EricWVGG commented
> VIdeos are to uploaded to Cloudinary, Component shows an error

please clarify with steps

2022-12-22 17:31 UTC, merged