Refresh user 2
artizen-fund/artizen-frontend pull request #323
Opened 2022-12-22 22:55 UTC by EricWVGG

The Apollo "reactive var" has no sense of when data is being updated, because it's designed to be a sort of unmanaged "store anything here" bucket, and thus wasn't updating with user settings changes.

I attempted to put in a thing that would update the reactive var manually when a user did a mutation on their self, but it just didn't work.

I wound up just ripping out the reactive var and replacing it with a normal Apollo request. I renamed GET_USER and UPDATE_USER with GET_SELF and UPDATE_SELF to distinguish things. (We do still have UDPATE_USERS for the new grant form).

We are doing updates based on `Users.publicAddress` instead of `Users.id` as the latter just didn't work for me. If that's a problem, I'll revisit it.

Please review the ApolloCache file because I don't really understand it at all.

(Along the way I also found a bunch of obsolete components and deleted them.)

2022-12-23 13:11 UTC, rubelux requested changes

2022-12-23 13:11 UTC, rubelux commented on src/gql/updateSelf.ts
> +export const UPDATE_SELF = gql`
UPDATE_SELF and UPDATE_USER are the same functions with different attributes.

it'd be more readable and scalable, having one single function and passing the whole variable from the Query function variable. 
GrapqlQL queries and mutations are generic, so it works better to keep them that way...

We do not want to grow the queries and mutations for each use case but rather have one mutation and query that covers everthing. 
Here we'¡d have a ```insert_Users``` -- You keep them as an array, pass the whole ```where```and the whole ```set```from the ```useMutation``` consumer...

2022-12-23 13:11 UTC, rubelux commented on src/gql/getSelf.ts
> +export const GET_SELF = gql`
```GET_SELF``` and ```GET_USER``` are the same functions with different attributes.

It'd be more readable and scalable, having one single function and passing the whole ```where```variable from the Query function variable.
GrapqlQL queries and mutations are generic, so it works better to keep them that way...

We do not want to grow the queries and mutations for each use case but rather have one mutation and query that covers everything.

2022-12-23 13:11 UTC, rubelux commented on src/lib/CourierNotification.tsx
> +  const { data: session } = useSession()
it seems we would have to call ```  const { data: session } = useSession()```and ```const { data: loggedInUser } = useQuery<IGetSelfQuery>(GET_SELF, {...``` every time we need to get the users. 

Can you wrap them into one single hook? This component will return ```loggedInUser``` ,  ```loading``` and ```error```

2022-12-23 13:11 UTC, rubelux commented on src/lib/apollo/cache.ts
>            keyArgs: ['where'],
it should be fine

2022-12-23 13:28 UTC, rubelux commented
@EricWVGG I love the idea of using the Apollo cache for the user; way better due to the reactive nature of Apollo anyway. My comments are mainly around all these new GraphQL queries and mutations. 

I see how we are creating new GraphQL functions for each use case. This approach breaks the generalist magic of  GraphQL. It scales better if we create generic functions and give the definition in the variables from the consumer, so instead of passing a ```publicAddress``` to a Users Query, just pass the whole ```where```and the conditional in it


```
useQuery(
    {
       variables: {
             where:  { 
                publicAddress:  { 
                 _eq: <Public Address >
               }  
          } 
       }
    }
)

```

Also, for the sake of simplicity, we can call the GraphQL functions precisely as their Hasura names but written in camel case, so if the Hasura name is ```insert_Users``` we can call it: ```ìnsertUser```
etc...

Also using array mutations and queries, makes the functions even more useful so ```insert_Users``` instead of ```insert_User_one``` or Query ```Users``` instead of Query ```Users_by_pk``` etc...

Finally, I suggested wrapping into a hook the hooks needed to grab the current user into one single hook so we do not need to load all those files every time we will check for the ```loggedUser```..

2022-12-23 21:51 UTC, EricWVGG commented on src/lib/CourierNotification.tsx
> +  const { data: session } = useSession()
I thought the way Apollo cache worked was, it would be smart enough not to redundant calls?

2022-12-23 21:52 UTC, EricWVGG commented on src/gql/getSelf.ts
> +export const GET_SELF = gql`
Are they different if GET_SELF has the USER_PUBLIC and USER_PRIVATE fragments, but GET_USER only has USER_PUBLIC?

2023-01-04 13:48 UTC, rubelux commented on src/gql/getSelf.ts
> +export const GET_SELF = gql`
@EricWVGG let's try to merge both of them into one function

2023-01-04 17:11 UTC, rubelux commented on src/gql/getSelf.ts
> +export const GET_SELF = gql`
@EricWVGG I am not sure; I think it'd complain but it'd be better to test it

2023-01-05 15:21 UTC, closed without merging