stuff
artizen-fund/artizen-frontend pull request #335
Opened 2023-01-04 16:01 UTC by EricWVGG

This disables a thing that puts the form into perpetual react updates, and correctly returns true when the participants form is valid.

2023-01-04 23:22 UTC, EricWVGG commented
edit: it now fixes an issue with creating a new grant.

2023-01-05 09:18 UTC, geometrizen commented
I tested this locally, and on my first attempt, I could not get grant creation to work. In particular the glitchy text input (which I think is related to the infinite loop that you all were referring to yesterday) is still occurring for me-- I'll post some screen capture videos in slack. 

Here are some other general notes:

I don't think the admin / curator user should be allowed to enter text for the 'date of grant' -- not sure when this changed but it needs to be fixed. (Way too many things that could go wrong with a general admin user entering a datetime here)

typo: "Longline" should be "Logline" (if necessary, check [Nene's comment on this google doc](https://docs.google.com/document/d/1WlGZQut9EqNyP3IciuIJbatLgGTsJoHbNuCInCX20YA/edit#heading=h.60q6srg0l06g))

Love the form validation errors being displayed, thank you 👍 (I haven't checked that this is working for all relevant fields, but I saw it working for at least one)

So, I don't think this should be merged yet. Please let me know if I'm missing something. I'll try creating a grant again, typing more slowly

2023-01-05 13:33 UTC, geometrizen commented
https://user-images.githubusercontent.com/102297373/210791663-cfc62f8a-dbaa-4ec2-a095-4470283d04cd.mov


https://user-images.githubusercontent.com/102297373/210791702-103c8529-fb77-4ac4-aa98-8e72c09e8590.mov

2023-01-05 13:34 UTC, geometrizen requested changes
Testing this locally did not work for me-- please see comment(s) in the general conversation of this PR.

2023-01-05 15:19 UTC, EricWVGG commented
- The text capture bug still exists in the current codebase, and is lessened with this PR, so it’s not a regression.
- If “longline” is supposed to be “logline” then that’s a typo in Hasura. It should be fixed as a separate branch.
- “admin curator shouldn’t enter text for date of grant” I thought I explained that, apologies if I overlooked it: it is supposed to be a pre-fill read-only field, but the text capture bug was leading that to an infinite loop.

Since this does enable the creation of grants, and that’s holding up a lot of important work, and none of this PR is a regression, I would like it to be merged so we can move forward with testing and fixing other things (yes, including deeper investigation of the text capture glitch)

2023-01-05 15:30 UTC, geometrizen approved these changes
looks okay and I won't block merging as I agree with Eric that we should test this on dev-- but I'm curious about my comments inline as well as the user-editability of the grant start date

2023-01-05 15:30 UTC, geometrizen commented on src/components/CreateGrants/NewGrantForm/index.tsx
> +  //     if (!validateLib.validate(data.project.walletAddress, 'ETH')) {
are we validating the wallet address elsewhere? validating the wallet address seems like a good thing to do

2023-01-05 15:30 UTC, geometrizen commented on src/components/CreateGrants/NewGrantForm/helpers/validators.ts
> +  return true
ah is this effectively where the wallet address validation is happening now?

2023-01-05 15:31 UTC, EricWVGG commented on src/components/CreateGrants/NewGrantForm/helpers/validators.ts
> +  return true
Yes.

2023-01-05 15:32 UTC, EricWVGG commented on src/components/CreateGrants/NewGrantForm/index.tsx
> +  //     if (!validateLib.validate(data.project.walletAddress, 'ETH')) {
The validation is contributing to the text capture bug.

2023-01-05 15:44 UTC, merged